- brand: RentACoop
  search_terms: ["RentACoop chicken feeder"]
- brand: Grandpa's Feeders
  search_terms: ["Grandpa's Feeders chicken feeder"]
- brand: Little Giant
  search_terms: ["Little Giant chicken feeder"]
- brand: Duncan's
  search_terms: ["Duncan's chicken feeder"]
- brand: Harris Farms
  search_terms: ["Harris Farms chicken feeder"]
