- brand: Brinsea
  search_terms: ["Brinsea egg incubator"]
- brand: Nurture Right
  search_terms: ["Nurture Right 360 egg incubator"]
- brand: Little Giant
  search_terms: ["Little Giant egg incubator"]
- brand: Harris Farms
  search_terms: ["Harris Farms egg incubator"]
