- brand: Premier 1
  search_terms: ["Premier 1 chicken waterer"]
- brand: Farm Innovators
  search_terms: ["Farm Innovators chicken waterer"]
- brand: OverEZ
  search_terms: ["OverEZ chicken waterer"]
- brand: RentACoop
  search_terms: ["RentACoop chicken waterer"]
- brand: Miller
  search_terms: ["Miller chicken waterer"]
